/**
 * 命名规则
 * @constants ======================================
 *
 * 增益命名规则
 * [buff名称]_[是否qidian]_INCREATED_[buff增益属性]_[百分比percent]/[等级level]
 * @param SANSHENG_QIDIAN_INCREASED_SOLARATTACKPOWERBASE_PERCENT
 */

/**
 * 三生每豆增加的基础攻击比例
 * @param SANSHENG_QIDIAN_INCREASED_SOLARATTACKPOWERBASE_PERCENT
 */
export const SANSHENG_QIDIAN_INCREASED_SOLARATTACKPOWERBASE_PERCENT = 0.08;

/**
 * 颂言每层3%会心 400攻击（吃三生）
 * @param SONGYAN_INCREASED_SOLARCRITICALSTRIKERATE
 * @param SONGYAN_INCREATED_SOLARATTACKPOWERBASE
 */
export const SONGYAN_INCREASED_SOLARCRITICALSTRIKERATE = 0.03;
export const SONGYAN_INCREATED_SOLARATTACKPOWERBASE = 400;

/**
 * @param SOLAROVERCOME_TRANSFORM_COE 破防等级转换破防系数
 * @param STRAIN_TRANSFORM_COE 无双等级转换无双系数
 * @param CRITICALSTRIKE_TRANSFORM_COE 会心等级转换会心系数
 * @param CRITICALSTRIKEDAMAGEPOWER_TRANSFORM_COE 会效等级转换会效系数
 */
export const SOLAROVERCOME_TRANSFORM_COE = 357.375;
export const STRAIN_TRANSFORM_COE = 344.5875;
export const CRITICALSTRIKE_TRANSFORM_COE = 357.375;
export const CRITICALSTRIKEDAMAGEPOWER_TRANSFORM_COE = 125.0625;
